<?php

/**
 * @file
 * Module file for the OSU Groups module.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\osu_groups\Hook\OsuGroupsFormHooks;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Most of this code was taken from the Drupal Redirect module.
 */
#[LegacyHook]
function osu_groups_form_group_form_alter(&$form, FormStateInterface $form_state) {
  Drupal::service(OsuGroupsFormHooks::class)->formGroupFormAlter($form, $form_state);
}
